---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: argocd-notifications-secret
  namespace: default
spec:
  encryptedData:
    slack-token: AgCEYQRCxLVvEt8rBLdf1uKTt1ufFbXCyHsQYlE+G6/MY1TlpS9YHI6B7k3EeeyOnaOdlC6jxgztYFLbA7xwYKDajaoJmSw9R8YtQv7LkwuL7hYE9Qy1xkOExUKtFiPX9cqA6O66yyVnpduv/tr/0rnBD3cSpOZ502hINF1eksJHpxoEr3/DurOVWTPVz9eZrc+5se4RG5jU+Wr6p/CO2fzbNqoROBcJ2pN/TWQqQQhiOVYlHMJpA5GKCZbdyfa3DAzCh9bQ8TcVOZ+Fh7xjRzKQH3YCygI+Qr4fghx2otTgxOv6eHepbmYkL4TieA588idR6T0AwJHhhhI67Jz3uYt9DT9cZY1LcWOOdWChrH/3vW5a3+RMMjh4Gwup6ie0UMgYM9cc6q6SQ4d+lKCWw51KQNyv42SD5smltJfxeaj6KYi9ZPRUmhrnkU47TAjvLD68Thh8COl7OiS2dLtuE9rpUATDtq/VFNfasBD5dkOhuyStQowhDdKUSF7OQBX6ILbHAAPIYZzsvdyrH1+/wMUx0/iMHawcPE/a0FdmWgYT8ox+hKmbrGHZHzRt+4Z0cyA8a94MdoqGN71NFkx5ldWjcQtxa0XQA+e2qEDFhM0596XB/iyjfUGyuZeWUo6/cqMEeJa2eSq/yK6+W1VL+YnKuKBW8hpdhsMT+PzO2xgZCatkYWu+LNHQF1b2HUbdFZC3gQfoa3SBXnh/+QIhZDcBEeIvfg==
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: my-argo-cd
        meta.helm.sh/release-namespace: default
        sealedsecrets.bitnami.com/cluster-wide: "true"
      labels:
        app.kubernetes.io/component: notifications-controller
        app.kubernetes.io/instance: my-argo-cd
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: argocd-notifications-controller
        app.kubernetes.io/part-of: argocd
        app.kubernetes.io/version: v3.3.5
        helm.sh/chart: argo-cd-9.4.16
      name: argocd-notifications-secret
      namespace: default
    type: Opaque
