apiVersion: v1
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: my-argo-cd
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2026-03-26T14:32:10Z"
  labels:
    app.kubernetes.io/component: notifications-controller
    app.kubernetes.io/instance: my-argo-cd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-notifications-controller
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v3.3.5
    helm.sh/chart: argo-cd-9.4.16
  name: argocd-notifications-secret
  namespace: default
  resourceVersion: "828"
  uid: a39eb46b-bbe1-4708-af79-6c05df82056f
type: Opaque
StringData:
    slack-token: <Oauth-access-token>