apiVersion: v1
kind: Secret
metadata:
  name: world-countries-secret
type: Opaque
stringData:
  MONGO_URI: "mongodb://mongodb-service:27017/worlddb"
  MONGO_USERNAME: "admin"
  MONGO_PASSWORD: "password"
 