apiVersion: v1
kind: Service
metadata:
  labels:
    app: world-countries
  name: world-countries
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 3000
  selector:
    app: world-countries
  type: NodePort
status:
  loadBalancer: {}
